image: python:3.6-stretch

stages:
  - test
  
before_script:
    - pip install -r requirements.txt
    
test:
  stage: test
  script:
    - gunicorn app:app
    
production:
    type: deploy
    stage: production
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - master
