apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-stations-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bus-stations-dev
  template:
    metadata:
      labels:
        app: bus-stations-dev
    spec:
      containers:
      - name: bus-stations-dev
        image: gcr.io/fit-api-256018/bus-stations-dev
        ports:
        - containerPort: 5000